const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');
const marked = require('marked');

async function convertToPDF() {
    // Read the index.html file
    const indexHtml = fs.readFileSync('index.html', 'utf8');
    const $ = cheerio.load(indexHtml);

    // Read the README.md content and parse it
    const readmeContent = fs.readFileSync('README.md', 'utf8');
    const htmlContent = marked.parse(readmeContent);

    // Read the profile image and convert to base64
    const imageBuffer = fs.readFileSync('me.jpg');
    const imageBase64 = `data:image/jpeg;base64,${imageBuffer.toString('base64')}`;

    // Replace the image src with base64
    $('img[src="me.jpg"]').attr('src', imageBase64);

    // Remove the website link from social links and add autogenerated notice at the top
    const autogeneratedNotice = `<div style="text-align: center; margin-bottom: 20px; font-size: 12px; color: #666; font-style: italic;">Autogenerated from website: <a href="https://ebetica.github.io/me/" style="color: #0066cc;">https://ebetica.github.io/me/</a></div>`;
    $('header').before(autogeneratedNotice);

    // Replace the dynamic content loading with static content
    $('#content').html(htmlContent);
    $('#error').remove();
    $('script').remove(); // Remove all scripts since we don't need them for PDF

    // Update the footer email
    $('footer').html('<strong>Contact:</strong> zeming@nyu.edu');

    // Add PDF-friendly style overrides
    const pdfStyles = `
        <style>
        /* PDF-friendly overrides */
        body {
            background-color: white !important;
            color: #333 !important;
            font-size: 14px !important;
            line-height: 1.8 !important;
            padding: 40px !important;
        }

        header {
            border-bottom: 2px solid #e0e0e0 !important;
            padding: 30px 0 !important;
            margin-bottom: 40px !important;
        }

        .name {
            color: #1a1a1a !important;
            font-size: 28px !important;
            gap: 20px !important;
        }

        .profile-photo {
            width: 60px !important;
            height: 60px !important;
            border: 2px solid #f0f0f0 !important;
        }

        .social-links {
            gap: 20px !important;
        }

        .social-links a {
            color: #555 !important;
            font-size: 18px !important;
        }

        .social-links a:hover {
            color: #0066cc !important;
        }

        footer {
            border-top: 2px solid #e0e0e0 !important;
            color: #666 !important;
            margin-top: 60px !important;
            padding-top: 30px !important;
        }

        .autogenerated-notice {
            text-align: center !important;
            margin-bottom: 20px !important;
            font-size: 12px !important;
            color: #666 !important;
            font-style: italic !important;
        }

        h1, h2, h3, h4, h5, h6 {
            color: #1a1a1a !important;
            margin-top: 30px !important;
            margin-bottom: 15px !important;
        }

        h1 { font-size: 24px !important; }
        h2 { font-size: 20px !important; }
        h3 { font-size: 18px !important; }

        hr {
            border-top: 1px solid #d0d0d0 !important;
            margin: 40px 0 !important;
        }

        code {
            background-color: #f5f5f5 !important;
            color: #333 !important;
            padding: 2px 6px !important;
            font-size: 13px !important;
        }

        pre {
            background-color: #f8f8f8 !important;
            padding: 20px !important;
            border: 1px solid #e0e0e0 !important;
        }

        pre code {
            background: none !important;
        }

        blockquote {
            border-left: 4px solid #0066cc !important;
            color: #555 !important;
        }

        a {
            color: #0066cc !important;
        }

        ul, ol {
            line-height: 1.8 !important;
            margin: 15px 0 !important;
        }

        li {
            margin: 8px 0 !important;
        }

        p {
            margin: 15px 0 !important;
            color: #333 !important;
        }

        @media print {
            body {
                padding: 20px !important;
            }
        }
        </style>
    `;

    // Add the PDF styles to the head
    $('head').append(pdfStyles);

    // Get the modified HTML
    const modifiedHtml = $.html();

    // Launch Puppeteer
    const browser = await puppeteer.launch({
        headless: 'new',
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    const page = await browser.newPage();

    // Set content
    await page.setContent(modifiedHtml, {
        waitUntil: 'networkidle0'
    });

    // Generate PDF
    await page.pdf({
        path: 'zeming-lin-cv.pdf',
        format: 'A4',
        margin: {
            top: '20mm',
            right: '20mm',
            bottom: '20mm',
            left: '20mm'
        },
        printBackground: true,
        preferCSSPageSize: false
    });

    await browser.close();

    console.log('PDF generated successfully: zeming-lin-cv.pdf');
}

convertToPDF().catch(console.error);